drv: net: phy: rtl8366_smi fix error when CONFIG_RTL8366_SMI_DEBUG_FS=y
drivers/net/phy/rtl8366_smi.c: In function ‘rtl8366_debugfs_init’:
drivers/net/phy/rtl8366_smi.c:942:14: error: invalid use of void expression
  942 |         node = debugfs_create_x16("reg", S_IRUGO | S_IWUSR, root,
      |              ^
drivers/net/phy/rtl8366_smi.c:966:14: error: invalid use of void expression
  966 |         node = debugfs_create_u8("vlan_4k_page", S_IRUGO | S_IWUSR, root,
      |              ^
make[5]: *** [scripts/Makefile.build:287: drivers/net/phy/rtl8366_smi.o] Error 1

After kernel 5.5, the two related functions no longer return values.